
Organizations:

  - &OrdererOrg
      
      Name: OrdererOrg

      ID: OrdererMSP
      
      MSPDir: crypto-config/ordererOrganizations/orderer.team3/msp
  
  - &Org1Team3

      Name: Org1Team3MSP

      ID: Org1Team3MSP

      MSPDir: crypto-config/peerOrganizations/org1.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051
    
  - &Org2Team3

      Name: Org2Team3MSP

      ID: Org2Team3MSP

      MSPDir: crypto-config/peerOrganizations/org2.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051

  - &Org3Team3

      Name: Org3Team3MSP

      ID: Org3Team3MSP

      MSPDir: crypto-config/peerOrganizations/org3.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051
  - &Org4Team3

      Name: Org4Team3MSP

      ID: Org4Team3MSP

      MSPDir: crypto-config/peerOrganizations/org4.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051
  - &Org5Team3

      Name: Org5Team3MSP

      ID: Org5Team3MSP

      MSPDir: crypto-config/peerOrganizations/org5.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051
  - &Org6Team3

      Name: Org6Team3MSP

      ID: Org6Team3MSP

      MSPDir: crypto-config/peerOrganizations/org6.team3/msp

      AnchorPeers:

        - Host: peer0.team3
          port: 7051

Application: &ApplicationDefaults

  Organizations:

Orderer: &OrdererDefaults

  OrdererType: solo
  Addresses:
    - orderer.team3:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations:
Profiles:
  OneOrgOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1Team3
          - *Org2Team3
          - *Org3Team3
          - *Org4Team3
          - *Org4Team3
          - *Org5Team3
          - *Org6Team3
  OneOrgChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1Team3
        - *Org2Team3
        - *Org3Team3
        - *Org4Team3
        - *Org4Team3
        - *Org5Team3
        - *Org6Team3       

