
OrdererOrgs:

  - Name: Team3
    Domain: team3
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: Team3
    Domain: team3
    Template:
      Count: 6
      Start: 0
      Hostname: .Prefix.Index
    Users:
      Count: 1  