
version: "2.2"

networks:
  main:

services:
  ca.team3.peer1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer1
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8001:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer1/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer1
    networks:
      - main
  ca.team3.peer2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer2
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8002:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer2/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer2
    networks:
      - main
  ca.team3.peer3:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer3
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8003:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer3/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer3
    networks:
      - main    
  ca.team3.peer4:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer4
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8004:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer4/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer4
    networks:
      - main
  ca.team3.peer5:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer5
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8005:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer5/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer5
    networks:
      - main
  ca.team3.peer6:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.team3.peer6
      - FABRIC_CA_SERVER_CA_CERTFILE=
      - FABRIC_CA_SERVER_CA_KEYFILE=
    ports:
      - "8006:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.team3.peer6/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.team3.peer6
    networks:
      - main
  orderer.team3:
    container_name: orderer.team3
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/team3/orderers/orderer.team3/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/team3.peer1/:/etc/hyperledger/msp/peer1
      - ./crypto-config/peerOrganizations/team3.peer2/:/etc/hyperledger/msp/peer2
      - ./crypto-config/peerOrganizations/team3.peer3/:/etc/hyperledger/msp/peer3
      - ./crypto-config/peerOrganizations/team3.peer4/:/etc/hyperledger/msp/peer4
      - ./crypto-config/peerOrganizations/team3.peer5/:/etc/hyperledger/msp/peer5
      - ./crypto-config/peerOrganizations/team3.peer6/:/etc/hyperledger/msp/peer6
  
  peer0.team3:
    container_name: peer0.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer0.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:6001
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer0.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb1
    networks:
      - main 
  peer1.team3:
    container_name: peer1.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer1.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:6002
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7052:7051
      - 7054:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer1.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb2
    networks:
      - main
  peer3.team3:
    container_name: peer3.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer3.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer3.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:6003
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7029:7051
      - 7056:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer3.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb3
    networks:
      - main
  peer4.team3:
    container_name: peer4.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer4.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer4.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:6004
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7057:7051
      - 7059:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer4.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb4
    networks:
      - main
  peer5.team3:
    container_name: peer5.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer5.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer5.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:6005
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7040:7051
      - 7058:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer5.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb5
    networks:
      - main 
  peer6.team3:
    container_name: peer6.team3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer6.team3
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_ADDRESS=peer6.team3:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:6006
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7010:7051
      - 7030:7053
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/team3/peers/peer6.team3/msp/:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/team3/peers/users/:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.team3
      - couchdb6
    networks:
      - main
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6001:5984
    networks:
      - main
  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6002:5984
    networks:
      - main
  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6003:5984
    networks:
      - main
  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6004:5984
    networks:
      - main
  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6005:5984
    networks:
      - main
  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6006:5984
    networks:
      - main
  cli:
    container_name: cli1
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.team3:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/team3/
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - main
